version: "3"

services:
  node:
    container_name: "docker-app"
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: "mongodb"
    image: mongo
    ports:
      - "27019:27017"
