version: '3'

services:
  web:
    container_name: docker-app
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo-docker
    image: mongo
    ports:
      - "27019:27017"